# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_for_dbg/clk_wiz_for_dbg.xci
# IP: The module: 'clk_wiz_for_dbg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_for_dbg/clk_wiz_for_dbg_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_for_dbg'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_for_dbg/clk_wiz_for_dbg.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_for_dbg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_for_dbg/clk_wiz_for_dbg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_for_dbg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_for_dbg/clk_wiz_for_dbg.xci
# IP: The module: 'clk_wiz_for_dbg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_for_dbg/clk_wiz_for_dbg_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_for_dbg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_for_dbg/clk_wiz_for_dbg.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_for_dbg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_for_dbg/clk_wiz_for_dbg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_for_dbg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
