# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_tran_rxclk/clk_wiz_tran_rxclk.xci
# IP: The module: 'clk_wiz_tran_rxclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_tran_rxclk/clk_wiz_tran_rxclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_tran_rxclk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_tran_rxclk/clk_wiz_tran_rxclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_tran_rxclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_tran_rxclk/clk_wiz_tran_rxclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_tran_rxclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_tran_rxclk/clk_wiz_tran_rxclk.xci
# IP: The module: 'clk_wiz_tran_rxclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_tran_rxclk/clk_wiz_tran_rxclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_tran_rxclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_tran_rxclk/clk_wiz_tran_rxclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_tran_rxclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_tran_rxclk/clk_wiz_tran_rxclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_tran_rxclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
