# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/udp.xdc

# XDC: new/si5338_xdc.xdc

# XDC: imports/new/false_path_from_timing_report.xdc

# IP: ip/ram/ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram || ORIG_REF_NAME==ram} -quiet] -quiet
