# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z035ffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/UDP_LOOP/UDP_LOOP.cache/wt [current_project]
set_property parent.project_path E:/UDP_LOOP/UDP_LOOP.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/UDP_LOOP/UDP_LOOP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/UDP_LOOP/UDP_LOOP.srcs/sources_1/imports/src_edit_by_vscode/ram_init.coe
add_files -quiet E:/UDP_LOOP/UDP_LOOP.runs/CRC32_D8_AAL5_synth_1/CRC32_D8_AAL5.dcp
set_property used_in_implementation false [get_files E:/UDP_LOOP/UDP_LOOP.runs/CRC32_D8_AAL5_synth_1/CRC32_D8_AAL5.dcp]
add_files -quiet E:/UDP_LOOP/UDP_LOOP.runs/ipsend_synth_1/ipsend.dcp
set_property used_in_implementation false [get_files E:/UDP_LOOP/UDP_LOOP.runs/ipsend_synth_1/ipsend.dcp]
read_mem E:/UDP_LOOP/UDP_LOOP.srcs/sources_1/imports/AX7350_Si5338_conf/si5338.mif
read_verilog -library xil_defaultlib {
  E:/UDP_LOOP/UDP_LOOP.srcs/sources_1/imports/src_edit_by_vscode/ipreceive.v
  E:/UDP_LOOP/UDP_LOOP.srcs/sources_1/imports/src_edit_by_vscode/rgmii_rx.v
  E:/UDP_LOOP/UDP_LOOP.srcs/sources_1/imports/src_edit_by_vscode/rgmii_tx.v
  E:/UDP_LOOP/UDP_LOOP.srcs/sources_1/imports/src_edit_by_vscode/udp.v
  E:/UDP_LOOP/UDP_LOOP.srcs/sources_1/imports/src_edit_by_vscode/ethernet_test_top.v
}
read_ip -quiet E:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/ram/ram.xci
set_property used_in_implementation false [get_files -all e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/ram/ram_ooc.xdc]

read_ip -quiet e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_tran_rxclk/clk_wiz_tran_rxclk.xci
set_property used_in_implementation false [get_files -all e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_tran_rxclk/clk_wiz_tran_rxclk_board.xdc]
set_property used_in_implementation false [get_files -all e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_tran_rxclk/clk_wiz_tran_rxclk.xdc]
set_property used_in_implementation false [get_files -all e:/UDP_LOOP/UDP_LOOP.srcs/sources_1/ip/clk_wiz_tran_rxclk/clk_wiz_tran_rxclk_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/UDP_LOOP/UDP_LOOP.srcs/constrs_1/new/udp.xdc
set_property used_in_implementation false [get_files E:/UDP_LOOP/UDP_LOOP.srcs/constrs_1/new/udp.xdc]

read_xdc E:/UDP_LOOP/UDP_LOOP.srcs/constrs_1/new/si5338_xdc.xdc
set_property used_in_implementation false [get_files E:/UDP_LOOP/UDP_LOOP.srcs/constrs_1/new/si5338_xdc.xdc]

read_xdc E:/UDP_LOOP/UDP_LOOP.srcs/constrs_1/imports/new/false_path_from_timing_report.xdc
set_property used_in_implementation false [get_files E:/UDP_LOOP/UDP_LOOP.srcs/constrs_1/imports/new/false_path_from_timing_report.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top RGMII_UDP_TEST -part xc7z035ffg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RGMII_UDP_TEST.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RGMII_UDP_TEST_utilization_synth.rpt -pb RGMII_UDP_TEST_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
